apiVersion: skaffold/v3
kind: Config
metadata:
  name: civicactions-content
build:
  artifacts:
  - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
    docker:
      dockerfile: Dockerfile.prod
  kaniko:
    namespace: civicactions-content
    pullSecretMountPath: /secret
    pullSecretPath: kaniko-secret
    cache:
      repo: gcr.io/ca-it-prod-shared-5a2c/civicactions-content-cache
manifests:
  rawYaml:
  - k8s/civicactions-content.yaml
deploy:
  kubectl: {}
