apiVersion: skaffold/v3
kind: Config
metadata:
  name: civicactions-content
build:
  artifacts:
    - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
      kaniko:
        dockerfile: Dockerfile.prod
        cache:
          repo: gcr.io/ca-it-prod-shared-5a2c/civicactions-content-cache
        imageFSExtractRetry: "2"
  cluster:
    namespace: civicactions-content
    pullSecretMountPath: /secret
    pullSecretPath: kaniko-secret
    pullSecretName: kaniko-secret
    concurrency: 0
    timeout: 60m
    randomDockerConfigSecret: false
    randomPullSecret: false
    resources:
      requests:
        memory: 2Gi
manifests:
  helm:
    releases:
      - name: "{{ .NAME }}"
        namespace: civicactions-content
        chartPath: k8s/strapi
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_gcr_io_ca_it_prod_shared_5a2c_civicactions_content }}"
        setValues:
          environment: review
          postgresql.enabled: true
deploy:
  kubectl: {}
profiles:
  - name: production
    manifests:
      helm:
        releases:
          - name: v4
            namespace: civicactions-content
            chartPath: k8s/strapi
            setValueTemplates:
              image: "{{ .IMAGE_FULLY_QUALIFIED_gcr_io_ca_it_prod_shared_5a2c_civicactions_content }}"
            setValues:
              environment: production
              databaseName: strapi4
              gcsBasePath: production
