apiVersion: skaffold/v3
kind: Config
metadata:
  name: civicactions-content
build:
  artifacts:
  - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
    kaniko:
      dockerfile: Dockerfile.prod
      cache:
        repo: gcr.io/ca-it-prod-shared-5a2c/civicactions-content-cache
  cluster:
    namespace: civicactions-content
    pullSecretMountPath: /secret
    pullSecretPath: kaniko-secret
    pullSecretName: kaniko-secret
    concurrency: 0
    randomDockerConfigSecret: false
    randomPullSecret: false
manifests:
  rawYaml:
  - k8s/civicactions-content.yaml
deploy:
  kubectl: {}
