apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-php
  namespace: civicactions-content
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
