apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: civicactions-content
  namespace: civicactions-content
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
