apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: civicactions-content
  namespace: civicactions-content
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_HOST
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_PASSWORD
            - name: GCS_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: GCS_SERVICE_ACCOUNT
            - name: USER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: USER_JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: ADMIN_JWT_SECRET
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: MAILGUN_API_KEY
