apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: v4
  namespace: civicactions-content
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: gcr.io/ca-it-prod-shared-5a2c/civicactions-content
          ports:
            - containerPort: 8080
          env:
            - name: URL
              # This should match https://<name>.<namespace>.app.civicactions.net
              value: https://v4.civicactions-content.app.civicactions.net
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_HOST
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_PASSWORD
            - name: DATABASE_DEBUG
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_DEBUG
            - name: STRAPI_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: STRAPI_LOG_LEVEL
            - name: GCS_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: GCS_SERVICE_ACCOUNT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: ADMIN_JWT_SECRET
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: APP_KEYS
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: API_TOKEN_SALT
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: MAILGUN_API_KEY
            - name: STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN
