apiVersion: batch/v1
kind: Job
metadata:
  name: v3-v4
  namespace: civicactions-content
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: upgrade
          image: gcr.io/ca-it-prod-shared-5a2c/v3-v4
          command: ["/opt/app/reset-schema.sh"]
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_HOST
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: DATABASE_PASSWORD
            - name: GCS_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: GCS_SERVICE_ACCOUNT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: ADMIN_JWT_SECRET
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: APP_KEYS
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: API_TOKEN_SALT
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: MAILGUN_API_KEY
            - name: STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: civicactions-content
                  key: STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN
