apiVersion: skaffold/v3
kind: Config
metadata:
  name: v3-v4
build:
  artifacts:
    - image: gcr.io/ca-it-prod-shared-5a2c/v3-v4
      kaniko:
        dockerfile: Dockerfile.prod
        cache:
          repo: gcr.io/ca-it-prod-shared-5a2c/civicactions-content-cache
        imageFSExtractRetry: "2"
  cluster:
    namespace: civicactions-content
    pullSecretMountPath: /secret
    pullSecretPath: kaniko-secret
    pullSecretName: kaniko-secret
    concurrency: 0
    timeout: 60m
    randomDockerConfigSecret: false
    randomPullSecret: false
    resources:
      requests:
        memory: 2Gi
manifests:
  rawYaml:
    - k8s-migrate-schema.yaml
deploy:
  kubectl: {}
