on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SKAFFOLD_VERSION: v1.22.0
      SKAFFOLD_HASH: 9bd85d4b31eeaea9e12d2f4f5128bfce8834a0fe7969101cbe994c04141af621
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
      # Log in to GCR with K8s Docker and Kaniko:
kubectl --dry-run=client -o yaml --namespace civicactions-content create secret docker-registry regcred --docker-server=gcr.io --docker-username=_json_key --docker-password="${GITHUB_ACTIONS_GCLOUD}" --docker-email=it+cicd-docker@civicactions.com | kubectl apply -f -
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v1
        with:
          namespace: 'civicactions-content'
          container-registry-url: 'gcr.io'
          container-registry-username: _json_key
          container-registry-password: ${{ secrets.GCR_KEY }}
          secret-name: 'regcred'
      - name: Auth Kaniko to GCR
        uses: azure/k8s-create-secret@v1
        with:
          namespace: 'civicactions-content'
          secret-type: 'generic'
          arguments:  --from-literal=kaniko-secret='${{ secrets.GCR_KEY }}'
          secret-name: kaniko-secret
        id: create-secret
      - name: Auth Docker to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - name: Download Skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/${{ env.SKAFFOLD_VERSION }}/skaffold-linux-amd64
      - name: Check and install Skaffold
        run: |
          echo "Checking hash before install"
          if [ "$(sha256sum < skaffold | head -c 64)" = "${{ env.SKAFFOLD_HASH }}" ]; then \
            sudo install skaffold /usr/local/bin/; \
          else \
            echo "Hash mismatch"; \
            exit 1; \
          fi
      - name: Run Skaffold
        run: skaffold run