on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SKAFFOLD_VERSION: v2.0.3
      SKAFFOLD_HASH: 7d544461d53d541a6c1e6ba721a8e9f502d6cb240453faf31513f9e4d9b157c1
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
      - name: Auth Kubernetes to GCR
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret docker-registry regcred \
          --docker-server=gcr.io \
          --docker-username=_json_key \
          --docker-password='${{ secrets.GCR_KEY }}' \
          --docker-email=cicd-docker@example.com | kubectl apply -f -
      - name: Auth Kaniko to GCR
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret generic kaniko-secret \
          --from-literal=kaniko-secret='${{ secrets.GCR_KEY }}' | kubectl apply -f -
      - name: Auth Docker to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - name: Download Skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/${{ env.SKAFFOLD_VERSION }}/skaffold-linux-amd64
      - name: Check and install Skaffold
        run: |
          echo "Checking hash before install"
          if [ "$(sha256sum < skaffold | head -c 64)" = "${{ env.SKAFFOLD_HASH }}" ]; then \
            sudo install skaffold /usr/local/bin/; \
          else \
            echo "Hash mismatch"; \
            exit 1; \
          fi
      - name: Add secrets
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret generic civicactions-content \
          --from-literal=JWT_SECRET='${{ secrets.JWT_SECRET }}' \
          --from-literal=ADMIN_JWT_SECRET='${{ secrets. ADMIN_JWT_SECRET}}' \
          --from-literal=DATABASE_HOST='${{ secrets.DATABASE_HOST }}' \
          --from-literal=DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' \
          --from-literal=DATABASE_DEBUG='${{ secrets.DATABASE_DEBUG }}' \
          --from-literal=STRAPI_LOG_LEVEL='${{ secrets.STRAPI_LOG_LEVEL }}' \
          --from-literal=APP_KEYS='${{ secrets.APP_KEYS }}' \
          --from-literal=API_TOKEN_SALT='${{ secrets.API_TOKEN_SALT }}' \
          --from-literal=MAILGUN_API_KEY='${{ secrets.MAILGUN_API_KEY }}' \
          --from-literal=STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN='${{ secrets.STRAPI_GITHUB_ACTIONS_TRIGGER_TOKEN }}' \
          --from-literal=GCS_SERVICE_ACCOUNT='${{ secrets.GCS_SERVICE_ACCOUNT }}' | kubectl apply -f -
      - name: Run Skaffold
        run: skaffold run
