on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: gcr.io/k8s-skaffold/skaffold:v1.22.0
      volumes:
        - ${{ github.workspace }}:/skaffold
    steps:
      - uses: actions/checkout@v1
      - run: skaffold build
      - run: skaffold deploy