on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SKAFFOLD_VERSION: v1.22.0
      SKAFFOLD_HASH: 9bd85d4b31eeaea9e12d2f4f5128bfce8834a0fe7969101cbe994c04141af621
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
      - name: Auth Kubernetes to GCR
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret docker-registry regcred \
          --docker-server=gcr.io \
          --docker-username=_json_key \
          --docker-password='${{ secrets.GCR_KEY }}' \
          --docker-email=cicd-docker@example.com | kubectl apply -f -
      - name: Auth Kaniko to GCR
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret generic kaniko-secret \
          --from-literal=kaniko-secret='${{ secrets.GCR_KEY }}' | kubectl apply -f -
      - name: Auth Docker to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - name: Download Skaffold
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/${{ env.SKAFFOLD_VERSION }}/skaffold-linux-amd64
      - name: Check and install Skaffold
        run: |
          echo "Checking hash before install"
          if [ "$(sha256sum < skaffold | head -c 64)" = "${{ env.SKAFFOLD_HASH }}" ]; then \
            sudo install skaffold /usr/local/bin/; \
          else \
            echo "Hash mismatch"; \
            exit 1; \
          fi
      - name: Add secrets
        run: |
          kubectl --dry-run=client -o yaml --namespace civicactions-content create secret generic civicactions-content \
          --from-literal=USER_JWT_SECRET='${{ secrets.USER_JWT_SECRET }}' \
          --from-literal=ADMIN_JWT_SECRET='${{ secrets. ADMIN_JWT_SECRET}}' \
          --from-literal=DATABASE_HOST='${{ secrets.DATABASE_HOST }}' \
          --from-literal=DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' \
          --from-literal=MAILGUN_API_KEY='${{ secrets.DATABASE_PASSWORD }}' \
          --from-literal=GCS_SERVICE_ACCOUNT='${{ secrets.GCS_SERVICE_ACCOUNT }}' | kubectl apply -f -
      - name: Run Skaffold
        run: skaffold run
