on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      SKAFFOLD_VERSION: v1.22.0
      SKAFFOLD_HASH: 9bd85d4b31eeaea9e12d2f4f5128bfce8834a0fe7969101cbe994c04141af621
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
      # Log in to GCR with local Docker and Kaniko:
      - uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_KEY }}
      - run: kubectl --dry-run=client -o yaml --namespace civicactions-content create secret generic kaniko-secret --from-literal=kaniko-secret='${{ secrets.GCR_KEY }}' | kubectl apply -f -
      - run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/${{ env.SKAFFOLD_VERSION }}/skaffold-linux-amd64
      - run: |
          echo "Checking hash before install"
          if [ "$(sha256sum < skaffold | head -c 64)" = "${{ env.SKAFFOLD_HASH }}" ]; then \
            sudo install skaffold /usr/local/bin/; \
          else \
            echo "Hash mismatch"; \
            exit 1; \
          fi
      - run: skaffold build --verbosity debug
      - run: skaffold deploy